MULTIBOOT_HEADER							equ 1

MULTIBOOT_HEADER_TAG_END					equ	0
MULTIBOOT_HEADER_TAG_INFORMATION_REQUEST	equ	1
MULTIBOOT_HEADER_TAG_ADDRESS				equ	2
MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS			equ	3
MULTIBOOT_HEADER_TAG_CONSOLE_FLAGS			equ	4
MULTIBOOT_HEADER_TAG_FRAMEBUFFER			equ	5
MULTIBOOT_HEADER_TAG_MODULE_ALIGN			equ	6
MULTIBOOT_HEADER_TAG_EFI_BS					equ	7
MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI32	equ	8
MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI64	equ	9
MULTIBOOT_HEADER_TAG_RELOCATABLE			equ	10
MULTIBOOT_HEADER_TAG_OPTIONAL				equ 1

bits 32
MAGIC		equ	0xE85250D6
ARCH		equ	0
HEADER_LEN	equ MULTIBOOT_END-MULTIBOOT_START
CHECKSUM	equ  0x100000000 - (MAGIC + ARCH + HEADER_LEN)

section .multiboot
MULTIBOOT_START:
align 8
	dd MAGIC
	dd ARCH
	dd HEADER_LEN
	dd CHECKSUM

	;;FRAMEBUFFER
align 8
FRAME_BUFFER_START:
	dw MULTIBOOT_HEADER_TAG_FRAMEBUFFER
	dw MULTIBOOT_HEADER_TAG_OPTIONAL
	dd FRAME_BUFFER_END-FRAME_BUFFER_START
	dd 1024
	dd 768
	dd 32
FRAME_BUFFER_END:

	;;FLAGS
align 8
CONSOLE_FLAGS_START:
	dw MULTIBOOT_HEADER_TAG_CONSOLE_FLAGS
	dw MULTIBOOT_HEADER_TAG_OPTIONAL
	dd CONSOLE_FLAGS_END-CONSOLE_FLAGS_START
	dd 0
CONSOLE_FLAGS_END:
align 8
	;;END
	dd 0
	dd 8
MULTIBOOT_END:
