#include "../../interrupts/idt.h"

#define ATAPIO_DRIVE_SELECT_PORT			0x1F6
#define ATAPIO_SECTOR_COUNT_PORT			0x1F2
#define ATAPIO_LBA_LOW_PORT					0x1F3
#define ATAPIO_LBA_MID_PORT					0x1F4
#define ATAPIO_LBA_HIGH_PORT				0x1F5
#define ATAPIO_COMMAND_PORT					0x1F7
#define ATAPIO_STATUS_PORT					0x1F7
#define ATAPIO_DATA_PORT					0x1F0
#define ATAPIO_ERROR_PORT					0x1F1


#define ATAPIO_MASTER_SELECT				0xA0
#define ATAPIO_SLAVE_SELECT					0xB0
#define ATAPIO_IDENTIFY_COMMAND				0xEC
#define ATAPIO_CACHE_FLUSH					0xE7

#define ATAPIO_STATUS_BUSY					0x80
#define ATAPIO_STATUS_ERROR					0x01
#define ATAPIO_STATUS_DRQ					0x08

#define ATAPIO_ALTERNATE_STATUS_REGISTER	0x3F6
#define ATAPIO_DEVICE_CONTROL_REGISTER		0x3F6
#define ATAPIO_DEVICE_ADDRESS_REGISTER		0x3F7

#define ATAPIO_ERROR_REGISTER_AMNF			1<<0
#define ATAPIO_ERROR_REGISTER_TKZNF			1<<1
#define ATAPIO_ERROR_REGISTER_ABRT			1<<2
#define ATAPIO_ERROR_REGISTER_MCR			1<<3
#define ATAPIO_ERROR_REGISTER_IDNF			1<<4
#define ATAPIO_ERROR_REGISTER_MC			1<<5
#define ATAPIO_ERROR_REGISTER_UNC			1<<6
#define ATAPIO_ERROR_REGISTER_BBK			1<<7

#define ATAPIO_READ_SECTORS_EXT				0x24
#define ATAPIO_WRITE_SECTORS_EXT			0x34

void ATAPIO_Identify(int target);

void ATAPIO_HANDLE_IRQ(registers* r);

uint16_t* ATAPIO_ReadBytes(int sectors,int lba);
